language: php
dist: trusty

git:
  depth: 5

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

jobs:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4snapshot
  fast_finish: true
  allow_failures:
    - php: 7.4snapshot

before_install:
  # disable Xdebug if present
  - phpenv config-rm xdebug.ini || echo "Xdebug not present"

install:
  - composer install --no-interaction --no-progress --prefer-dist --ansi

script:
  - vendor/bin/phpunit
